### PR TITLE
add Azure AD authentication

### PR DESCRIPTION
**Pull request by baoduy**
As current IODC got an issue when login with Azure AD. I have created this to Pull Request to support Azure AD authentication.  This also resolves issue #1039 had been raised by me.

### CODE REVIEW

**Review by rickbergfalk — CHANGES_REQUESTED** [review]
Thanks for this @baoduy! Could you /revert the `.gitignore` `settings.json` and `package-lock.json` changes?  Would be happy to pull this in once addressed :)

**Comment by baoduy** [comment]
> Thanks for this @baoduy! Could you /revert the `.gitignore` `settings.json` and `package-lock.json` changes? Would be happy to pull this in once addressed :)

Hi @rickbergfalk 
Thank you so much. I have reverted the changes for mentioned files. :)

**Comment by rickbergfalk** [comment]
Hi @baoduy - I still see the package-lock.json files in changes. Can that be reverted too?

**Comment by baoduy** [comment]
> Hi @baoduy - I still see the package-lock.json files in changes. Can that be reverted too?

My bad. I forgot to revert the package-lock.json inside client and server folders. Please help to review again.

**Comment by rickbergfalk** [comment]
Thanks @baoduy. Looks like test is failing for node 14. Will try to look into this later this week

**Comment by rickbergfalk** [comment]
Thanks @baoduy! just needed to clear the cache for CI to fix tests.

**Pull request merged**
