### PR TITLE
all md file in root repo translated to spanish

### PR DESCRIPTION
**Pull request by johnfelipe**
Signed-off-by: felipe <ingenierofelipeurrego@gmail.com>

### CODE REVIEW

**Comment by rickbergfalk** [comment]
Thanks @johnfelipe. Out of curiosity how were these translated?

Something I'm trying to figure out is how this would work as docs are updated. I don't have the bandwidth to maintain multiple copies of docs.

**Comment by johnfelipe** [comment]
U only change English versión I will translate to es, fr and it

**Comment by rickbergfalk** [comment]
@johnfelipe were these translated via an automated tool? I'm a bit hesitant to merge this. Not everything is translated and it could lead to outdated and cluttered files. 

If these were done with an automated tool, couldn't these be translated ad-hoc as someone needs?

**Comment by johnfelipe** [comment]
With Watson and next human, for latin American people
I want translate to es, fr and it UI, how that is possible?

**Comment by rickbergfalk** [comment]
Hi @johnfelipe - I appreciate the contribution here but I'm going to close this out. SQLPad development is slowing and I'd like to reduce and simplify the repo if possible.

**Pull request closed without merging**
