### PR TITLE
Test mariadb

### PR DESCRIPTION
**Pull request by eladeyal-intel**

### CODE REVIEW

**Review by dengc367 — APPROVED** [review]

**Comment by rickbergfalk** [comment]
Thanks for this @eladeyal-intel -- bummed this is a Sequelize issue. That library has a growing backlog of open PRs which is unfortunate to see.

**Comment by eladeyal-intel** [comment]
I am not sure why you merged this. Now ci will fail. Unfortunately I have no idea how to fix (except documenting unsupported mariadb version)

@rickbergfalk

**Comment by rickbergfalk** [comment]
I merged because it reflects the current state of things.

**Comment by rickbergfalk** [comment]
Oh and as for fix... I'm not super excited to do this but I'm contemplating forking sequelize...

**Pull request merged**
