### PR TITLE
Fix api userid data type issue

### PR DESCRIPTION
**Pull request by WolfeeLuo**
#1038 
basically this PR is to fix issue # 1038

### CODE REVIEW

**Review by rickbergfalk — COMMENTED** [review]
Sorry for delay in getting to this @WolfeeLuo! Instead of writing a migration, could we instead cast user.id to string in the comparison with `(batch.userId !== user.id.toString())`?

I'd be okay with the migration if we could somehow add a test with some pre-existing data before this migration runs for each DB.

My concern is mostly with SQLite and Sequelize. I've come across a lot of bugs when altering tables and I've become a bit hesitant to alter tables if we can avoid it.

**Comment by WolfeeLuo** [comment]
Hi @rickbergfalk. Thanks for the reply. 
Actually, type casting with `toString()` method can fix this issue. 
but considering system consistency and elegance, I chose the migration. 
I think `service-token` and `user` should use similar schema as the codes handle API request and user request are not separated.
But, yes....migration may cause some potential issues, especially under mssql because of it's constraints.
If you really concern subsequent issue, I'm OK to close this PR and fix this issue via type casting in code.

**Comment by rickbergfalk** [comment]
@WolfeeLuo I agree that a UUID would be more consistent... I will see if I can write a test for this before I tag next version.

Could you fix lint? I will merge once checks are green :)

**Comment by WolfeeLuo** [comment]
Hi @rickbergfalk , lint has been fixed.
thanks.

**Review by rickbergfalk — APPROVED** [review]

**Comment by rickbergfalk** [comment]
Thanks @WolfeeLuo!

**Pull request merged**
